name: bloc_library
description: A new Flutter project.

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.1.0
  flutter_bloc: ^0.6.0
  flutter:
    sdk: flutter
  todos_app_core:
    path: ../todos_app_core
  todos_repository_simple:
    path: ../todos_repository_simple

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_tests:
    path: ../integration_tests

flutter:
  uses-material-design: true
