name: todos_repository_core
description: An app-agnostic data source that can be used by all implementations

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta:

dev_dependencies:
  mockito:
