name: redurx_sample
description: An example Todo app created with redurx

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_redurx: ^0.4.2+1
  built_value: ^6.1.2
  built_collection: ^4.0.0
  tuple: ^1.0.2
  flutter_architecture_samples:
    path: ../../
  todos_repository:
    path: ../todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.1+1
  built_value_generator: ^6.1.2
  source_gen: ^0.9.0+1
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_driver:
    sdk: flutter
  integration_tests:
    path: ../integration_tests

dependency_overrides:
  analyzer: ^0.33.0

flutter:
  uses-material-design: true