name: blocs
description: The Business Logic Components for a Todo App

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  todos_repository_core:
    path: ../todos_repository_core
  rxdart: ^0.23.1

dev_dependencies:
  test:
  mockito:
